module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: '../src',
  testRegex: '.*\\.spec\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: ['**/*.(t|j)s'],
  coveragePathIgnorePatterns: [
    '.module.ts',
    'index.ts',
    'main.ts',
    'configuration.ts',
    '.validation.ts',
    '.event.ts',
    '.token.ts',
    '-integration.ts',
    '.interface.ts',
    'console.ts',
    'strategy.ts',
    '.dto.ts',
    'tests/data/*',
    '.config.ts',
    '.enum.ts',
    '.decorator.ts',
    '.e2e-spec.ts$',
    'src/midtrans/interface/*',
    'src/midtrans/testData/*',
    '.d.ts',
  ],
  coverageDirectory: '../coverage',
  testEnvironment: 'node',
  moduleNameMapper: {},
};
